FROM ubuntu:20.04

LABEL SOFTWARE_NAME mgltools
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "1.5.7"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C
ENV PATH="/mgltools/bin:${PATH}"
ENV LIBGL_ALWAYS_INDIRECT=1

RUN     apt-get clean && \
        rm -r /var/lib/apt/lists/*

RUN     . /etc/os-release \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME} main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-backports main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> mirror.txt && \
        mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        cat mirror.txt /etc/apt/sources.list.bak > /etc/apt/sources.list && \
        apt-get update && apt-get upgrade -y --fix-missing

RUN     apt-get update && apt-get install -y  --no-install-recommends \
            build-essential \
            ca-certificates \
            dbus \
            libgl1 \
            libgl1-mesa-glx \
            libglu1-mesa \
            libx11-6 \
            libxi6 \
            libxmu6 \
            mesa-utils \
            wget

RUN     mkdir /mgltools && \
        wget -O "/mgl.tar.gz" \
            --no-check-certificate \
            https://ccsb.scripps.edu/download/532/ && \
        tar -zxf /mgl.tar.gz \
            -C /mgltools \
            --strip-components 1 && \
        rm /mgl.tar.gz && \
        ls /mgltools


WORKDIR /mgltools
RUN     ls -lh
RUN     ./install.sh

ENTRYPOINT ["/mgltools/bin/adt"]